# Cloudflare Pages Configuration for DeepHand
name = "deephand-web"
compatibility_date = "2025-06-15"

# Pages build output directory
pages_build_output_dir = "dist"


# Secrets (encrypted variables) - configured via Cloudflare dashboard
# RESEND_API_KEY (configured as secret in Cloudflare)
RESEND_API_KEY=re_hgnJrhkJ_6ZFZYbP96LKF7ywdLTzUWHP9


# Environment variables binding
# These variables will be available in the runtime as process.env
[vars]
PUBLIC_SITE_URL = "https://deephandai.com"
ADMIN_EMAIL = "contact@deephandai.com"
FROM_EMAIL = "contact@deephandai.com"
NOREPLY_EMAIL = "noreply@deephandai.com"
REQUESTS_EMAIL = "requests@deephandai.com"
NODE_ENV = "production"
